# Generated by Django 2.2.4 on 2020-07-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comarket', '0002_mercado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercado',
            name='imagen',
            field=models.BinaryField(blank=True),
        ),
    ]
