# Generated by Django 2.2.4 on 2020-07-10 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comarket', '0004_auto_20200709_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mercado',
            name='imagen',
        ),
    ]
