# Generated by Django 2.2.4 on 2020-07-10 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comarket', '0005_remove_mercado_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foro',
            name='fecha',
        ),
    ]
